/* Generated By:JJTree: Do not edit this line. ASTassignSingle.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTassignSingle extends SimpleNode {
  public ASTassignSingle(int id) {
    super(id);
  }

  public ASTassignSingle(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ab2593390620492062a523594dd65b24 (do not edit this line) */
