/* Generated By:JJTree: Do not edit this line. ASTatomic.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTatomic extends SimpleNode {
  public ASTatomic(int id) {
    super(id);
  }

  public ASTatomic(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b89db4c375464556897148a2cfc4df28 (do not edit this line) */
