/* Generated By:JJTree: Do not edit this line. ASTalgorithmName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTalgorithmName extends SimpleNode {
  public ASTalgorithmName(int id) {
    super(id);
  }

  public ASTalgorithmName(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9de87604a423fd105a66cd33d0667da5 (do not edit this line) */
