/* Generated By:JJTree: Do not edit this line. ASTalgorithm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTalgorithm extends SimpleNode {
  public ASTalgorithm(int id) {
    super(id);
  }

  public ASTalgorithm(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ced31e4d2bcafb7df1c2127fd3e95edf (do not edit this line) */
