/* Generated By:JJTree: Do not edit this line. ASTarguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarguments extends SimpleNode {
  public ASTarguments(int id) {
    super(id);
  }

  public ASTarguments(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb7652934fcc819d86008ae210175034 (do not edit this line) */
