/* Generated By:JJTree: Do not edit this line. ASTbound.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbound extends SimpleNode {
  public ASTbound(int id) {
    super(id);
  }

  public ASTbound(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=23c171965580c0d79057c0339b8213b8 (do not edit this line) */
