/* Generated By:JJTree: Do not edit this line. ASTbranch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbranch extends SimpleNode {
  public ASTbranch(int id) {
    super(id);
  }

  public ASTbranch(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ac69591d2a848c7fc84743a33c38dcf (do not edit this line) */
