/* Generated By:JJTree: Do not edit this line. ASTbranchArm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbranchArm extends SimpleNode {
  public ASTbranchArm(int id) {
    super(id);
  }

  public ASTbranchArm(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ccd35c2f592493dea8881ab99c5b879 (do not edit this line) */
