/* Generated By:JJTree: Do not edit this line. ASTbounds.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbounds extends SimpleNode {
  public ASTbounds(int id) {
    super(id);
  }

  public ASTbounds(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=297d1b094643e1d0f1c6aee9660991eb (do not edit this line) */
