/* Generated By:JJTree: Do not edit this line. ASTconfig.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconfig extends SimpleNode {
  public ASTconfig(int id) {
    super(id);
  }

  public ASTconfig(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=65034b4015fd231d8ef95c9e7dc7d2d5 (do not edit this line) */
