/* Generated By:JJTree: Do not edit this line. ASTcaseExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcaseExpression extends SimpleNode {
  public ASTcaseExpression(int id) {
    super(id);
  }

  public ASTcaseExpression(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9aa6fbdb8bc888cc16083ee1c7baca94 (do not edit this line) */
