/* Generated By:JJTree: Do not edit this line. ASTcaseArm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcaseArm extends SimpleNode {
  public ASTcaseArm(int id) {
    super(id);
  }

  public ASTcaseArm(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5d192952030afffe9b6565e9570b203 (do not edit this line) */
