/* Generated By:JJTree: Do not edit this line. ASTcondExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcondExpression extends SimpleNode {
  public ASTcondExpression(int id) {
    super(id);
  }

  public ASTcondExpression(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e482c1bd7316c2e94b00c5b381a1ac6 (do not edit this line) */
