/* Generated By:JJTree: Do not edit this line. ASTconstraint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconstraint extends SimpleNode {
  public ASTconstraint(int id) {
    super(id);
  }

  public ASTconstraint(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e90cd481ab33ec9d709569e000da0aed (do not edit this line) */
