/* Generated By:JJTree: Do not edit this line. ASTconstantDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconstantDef extends SimpleNode {
  public ASTconstantDef(int id) {
    super(id);
  }

  public ASTconstantDef(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57aeafcb5a017b3f65891655c3c2efc9 (do not edit this line) */
