/* Generated By:JJTree: Do not edit this line. ASTconstantDefs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconstantDefs extends SimpleNode {
  public ASTconstantDefs(int id) {
    super(id);
  }

  public ASTconstantDefs(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba9971f9c9f7aab1bd13cd9a01beccf1 (do not edit this line) */
