/* Generated By:JJTree: Do not edit this line. ASTdefDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdefDecl extends SimpleNode {
  public ASTdefDecl(int id) {
    super(id);
  }

  public ASTdefDecl(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d477c1c4fc3c8308626b8448360e2066 (do not edit this line) */
