/* Generated By:JJTree: Do not edit this line. ASTeither.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTeither extends SimpleNode {
  public ASTeither(int id) {
    super(id);
  }

  public ASTeither(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=370e14f1ede3bd0b9e9a029a0ca8aa93 (do not edit this line) */
