/* Generated By:JJTree: Do not edit this line. ASTexpAtomic.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTexpAtomic extends SimpleNode {
  public ASTexpAtomic(int id) {
    super(id);
  }

  public ASTexpAtomic(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a14c631a5fcbb31e989083aaf50a74cf (do not edit this line) */
