/* Generated By:JJTree: Do not edit this line. ASTforeach.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTforeach extends SimpleNode {
  public ASTforeach(int id) {
    super(id);
  }

  public ASTforeach(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cee2627e60afcc17924f12f26c247ec0 (do not edit this line) */
