/* Generated By:JJTree: Do not edit this line. ASTfunctExcept.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctExcept extends SimpleNode {
  public ASTfunctExcept(int id) {
    super(id);
  }

  public ASTfunctExcept(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=07531cca8ee5555ab8f399059d8bb24a (do not edit this line) */
