/* Generated By:JJTree: Do not edit this line. ASTfunctDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctDecl extends SimpleNode {
  public ASTfunctDecl(int id) {
    super(id);
  }

  public ASTfunctDecl(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=74cef9094911a6dfbd68c57c51f8488a (do not edit this line) */
