/* Generated By:JJTree: Do not edit this line. ASTfunctConstruction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctConstruction extends SimpleNode {
  public ASTfunctConstruction(int id) {
    super(id);
  }

  public ASTfunctConstruction(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01c78a7afbfd367fad7944fbddb622f9 (do not edit this line) */
