/* Generated By:JJTree: Do not edit this line. ASTfunctSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctSet extends SimpleNode {
  public ASTfunctSet(int id) {
    super(id);
  }

  public ASTfunctSet(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c596a030cebea4629fff3ab8993a3e87 (do not edit this line) */
