/* Generated By:JJTree: Do not edit this line. ASTfairness.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfairness extends SimpleNode {
  public ASTfairness(int id) {
    super(id);
  }

  public ASTfairness(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=abad5317f2bb42d92a6051005367a432 (do not edit this line) */
