/* Generated By:JJTree: Do not edit this line. ASTfunctionDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctionDefinition extends SimpleNode {
  public ASTfunctionDefinition(int id) {
    super(id);
  }

  public ASTfunctionDefinition(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70c3930894a550d8a98571efd7be0fcf (do not edit this line) */
