/* Generated By:JJTree: Do not edit this line. ASTheader.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTheader extends SimpleNode {
  public ASTheader(int id) {
    super(id);
  }

  public ASTheader(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c92918cf3808149ccdc4ecb85098dc0c (do not edit this line) */
