/* Generated By:JJTree: Do not edit this line. ASTheader_constants.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTheader_constants extends SimpleNode {
  public ASTheader_constants(int id) {
    super(id);
  }

  public ASTheader_constants(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f6901a2cedc7486aaec0ed3a24c3801 (do not edit this line) */
