/* Generated By:JJTree: Do not edit this line. ASTheader_extends.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTheader_extends extends SimpleNode {
  public ASTheader_extends(int id) {
    super(id);
  }

  public ASTheader_extends(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cfb14fcef13a127206ceea92bf69b49c (do not edit this line) */
