/* Generated By:JJTree: Do not edit this line. ASTinstance.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTinstance extends SimpleNode {
  public ASTinstance(int id) {
    super(id);
  }

  public ASTinstance(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=74930883116f4f920b1986d9ea9c896a (do not edit this line) */
