/* Generated By:JJTree: Do not edit this line. ASTidOrOpdecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTidOrOpdecl extends SimpleNode {
  public ASTidOrOpdecl(int id) {
    super(id);
  }

  public ASTidOrOpdecl(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d5e7ae74d72e5aa798e632fdfddbe2ee (do not edit this line) */
