/* Generated By:JJTree: Do not edit this line. ASTinfixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTinfixOperator extends SimpleNode {
  public ASTinfixOperator(int id) {
    super(id);
  }

  public ASTinfixOperator(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f2c45df88352195d141aedf5ace63ce (do not edit this line) */
