/* Generated By:JJTree: Do not edit this line. ASTifelse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTifelse extends SimpleNode {
  public ASTifelse(int id) {
    super(id);
  }

  public ASTifelse(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6214fc32d6e43182ea9b538a546dc59 (do not edit this line) */
