/* Generated By:JJTree: Do not edit this line. ASTinstruction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTinstruction extends SimpleNode {
  public ASTinstruction(int id) {
    super(id);
  }

  public ASTinstruction(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=279a51d2f00742f39add3428fdbee595 (do not edit this line) */
