/* Generated By:JJTree: Do not edit this line. ASTinvariant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTinvariant extends SimpleNode {
  public ASTinvariant(int id) {
    super(id);
  }

  public ASTinvariant(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a71fcce03f551fd894fc815c9ead69e9 (do not edit this line) */
