/* Generated By:JJTree: Do not edit this line. ASTloop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTloop extends SimpleNode {
  public ASTloop(int id) {
    super(id);
  }

  public ASTloop(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=865cdeeb201b095533e229815117c0dc (do not edit this line) */
