/* Generated By:JJTree: Do not edit this line. ASTmodel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmodel extends SimpleNode {
  public ASTmodel(int id) {
    super(id);
  }

  public ASTmodel(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=707122affd7b64b766e07dccd3fd2592 (do not edit this line) */
