/* Generated By:JJTree: Do not edit this line. ASTnonfixLHS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnonfixLHS extends SimpleNode {
  public ASTnonfixLHS(int id) {
    super(id);
  }

  public ASTnonfixLHS(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb9acd9bb8e611c83e7b32bee618ccc3 (do not edit this line) */
