/* Generated By:JJTree: Do not edit this line. ASToperatorDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASToperatorDefinition extends SimpleNode {
  public ASToperatorDefinition(int id) {
    super(id);
  }

  public ASToperatorDefinition(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d591904f2aed3fc6ef3ce40ac0e70bd7 (do not edit this line) */
