/* Generated By:JJTree: Do not edit this line. ASToverride.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASToverride extends SimpleNode {
  public ASToverride(int id) {
    super(id);
  }

  public ASToverride(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f190ef14c8688076efecb96e4cddecc (do not edit this line) */
