/* Generated By:JJTree: Do not edit this line. ASTparamInstances.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparamInstances extends SimpleNode {
  public ASTparamInstances(int id) {
    super(id);
  }

  public ASTparamInstances(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3b04da157a5cd424f5301a6a7281507 (do not edit this line) */
