/* Generated By:JJTree: Do not edit this line. ASTpBreak.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTpBreak extends SimpleNode {
  public ASTpBreak(int id) {
    super(id);
  }

  public ASTpBreak(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=571d5881fc3c2e3dea412a72ae512689 (do not edit this line) */
