/* Generated By:JJTree: Do not edit this line. ASTproperty.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTproperty extends SimpleNode {
  public ASTproperty(int id) {
    super(id);
  }

  public ASTproperty(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90a2376e6982da6664bbfc772d57671f (do not edit this line) */
