/* Generated By:JJTree: Do not edit this line. ASTPREFIX.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPREFIX extends SimpleNode {
  public ASTPREFIX(int id) {
    super(id);
  }

  public ASTPREFIX(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6e7fd34de9d3c11568fb33e07228b3c (do not edit this line) */
