/* Generated By:JJTree: Do not edit this line. ASTprocess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprocess extends SimpleNode {
  public ASTprocess(int id) {
    super(id);
  }

  public ASTprocess(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=373bfb98108a103b50f6d7abf358786b (do not edit this line) */
