/* Generated By:JJTree: Do not edit this line. ASTprint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprint extends SimpleNode {
  public ASTprint(int id) {
    super(id);
  }

  public ASTprint(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=91084626c456f68a165c0b3f5dfa17c6 (do not edit this line) */
