/* Generated By:JJTree: Do not edit this line. ASTprocessHeader.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprocessHeader extends SimpleNode {
  public ASTprocessHeader(int id) {
    super(id);
  }

  public ASTprocessHeader(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ace0c05944276c3e3bc7dff4f298d664 (do not edit this line) */
