/* Generated By:JJTree: Do not edit this line. ASTparamInstance.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparamInstance extends SimpleNode {
  public ASTparamInstance(int id) {
    super(id);
  }

  public ASTparamInstance(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19acf6affae68fd993fd46b6d6051e80 (do not edit this line) */
