/* Generated By:JJTree: Do not edit this line. ASTprefixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprefixOperator extends SimpleNode {
  public ASTprefixOperator(int id) {
    super(id);
  }

  public ASTprefixOperator(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99932b8b70e96fdb5c5930f213d63aa5 (do not edit this line) */
