/* Generated By:JJTree: Do not edit this line. ASTpropertySectionOutsideProcess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTpropertySectionOutsideProcess extends SimpleNode {
  public ASTpropertySectionOutsideProcess(int id) {
    super(id);
  }

  public ASTpropertySectionOutsideProcess(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9892abe497f5dc258ca30ddc888ea9ac (do not edit this line) */
