/* Generated By:JJTree: Do not edit this line. ASTprocedureCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprocedureCall extends SimpleNode {
  public ASTprocedureCall(int id) {
    super(id);
  }

  public ASTprocedureCall(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=43b9bd9f703f15114d4061651adf263a (do not edit this line) */
