/* Generated By:JJTree: Do not edit this line. ASTpReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTpReturn extends SimpleNode {
  public ASTpReturn(int id) {
    super(id);
  }

  public ASTpReturn(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a471045a4bacbbe320cd5d6024d2b5b (do not edit this line) */
