/* Generated By:JJTree: Do not edit this line. ASTpAssert.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTpAssert extends SimpleNode {
  public ASTpAssert(int id) {
    super(id);
  }

  public ASTpAssert(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dc88bfd7a446df907e46590a73f42b61 (do not edit this line) */
