/* Generated By:JJTree: Do not edit this line. ASTpostfixOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTpostfixOperator extends SimpleNode {
  public ASTpostfixOperator(int id) {
    super(id);
  }

  public ASTpostfixOperator(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c7ef9d82dd02cab114039271258c34c (do not edit this line) */
