/* Generated By:JJTree: Do not edit this line. ASTparamDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparamDecl extends SimpleNode {
  public ASTparamDecl(int id) {
    super(id);
  }

  public ASTparamDecl(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc127a13eac617d1bbe95f96cadb59af (do not edit this line) */
