/* Generated By:JJTree: Do not edit this line. ASTpGoto.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTpGoto extends SimpleNode {
  public ASTpGoto(int id) {
    super(id);
  }

  public ASTpGoto(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2574a82cb77499c134794374a938b19b (do not edit this line) */
