/* Generated By:JJTree: Do not edit this line. ASTrecord.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrecord extends SimpleNode {
  public ASTrecord(int id) {
    super(id);
  }

  public ASTrecord(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=962617fe8a8e2838fb0f85a358f1de27 (do not edit this line) */
