/* Generated By:JJTree: Do not edit this line. ASTrecordConstruction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrecordConstruction extends SimpleNode {
  public ASTrecordConstruction(int id) {
    super(id);
  }

  public ASTrecordConstruction(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2bf56592c40d65d52a7f80d202bda545 (do not edit this line) */
