/* Generated By:JJTree: Do not edit this line. ASTrun.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrun extends SimpleNode {
  public ASTrun(int id) {
    super(id);
  }

  public ASTrun(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0bccd4901262053f633d1ac02c127e7e (do not edit this line) */
