/* Generated By:JJTree: Do not edit this line. ASTrecordSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrecordSet extends SimpleNode {
  public ASTrecordSet(int id) {
    super(id);
  }

  public ASTrecordSet(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db2070218fb77eb6497bed351ce3fdbc (do not edit this line) */
