/* Generated By:JJTree: Do not edit this line. ASTsetEnumeration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsetEnumeration extends SimpleNode {
  public ASTsetEnumeration(int id) {
    super(id);
  }

  public ASTsetEnumeration(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7d00858b669ef1b009e1ca30746cb399 (do not edit this line) */
