/* Generated By:JJTree: Do not edit this line. ASTsetComprehension.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsetComprehension extends SimpleNode {
  public ASTsetComprehension(int id) {
    super(id);
  }

  public ASTsetComprehension(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed52a031e54ea854c1f5c88dbb32826c (do not edit this line) */
