/* Generated By:JJTree: Do not edit this line. ASTsourcefile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsourcefile extends SimpleNode {
  public ASTsourcefile(int id) {
    super(id);
  }

  public ASTsourcefile(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4de3566f3440c0c97cf5a220c38fcf2d (do not edit this line) */
