/* Generated By:JJTree: Do not edit this line. ASTselector.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTselector extends SimpleNode {
  public ASTselector(int id) {
    super(id);
  }

  public ASTselector(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=87a14feb207c4cb00eb1b878a35efa8e (do not edit this line) */
