/* Generated By:JJTree: Do not edit this line. ASTskip.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskip extends SimpleNode {
  public ASTskip(int id) {
    super(id);
  }

  public ASTskip(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=522671e37b631669e87445e74bbb1911 (do not edit this line) */
