/* Generated By:JJTree: Do not edit this line. ASTsymmetry.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsymmetry extends SimpleNode {
  public ASTsymmetry(int id) {
    super(id);
  }

  public ASTsymmetry(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e1b8419731ae48a4efbbefe5fe5b26b (do not edit this line) */
