/* Generated By:JJTree: Do not edit this line. ASTstatements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatements extends SimpleNode {
  public ASTstatements(int id) {
    super(id);
  }

  public ASTstatements(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9436fd766963f1d73922411598c99f56 (do not edit this line) */
