/* Generated By:JJTree: Do not edit this line. ASTtemporal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtemporal extends SimpleNode {
  public ASTtemporal(int id) {
    super(id);
  }

  public ASTtemporal(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3e82a178dcd7050926dfa2f31a1e076 (do not edit this line) */
