/* Generated By:JJTree: Do not edit this line. ASTvarDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvarDecl extends SimpleNode {
  public ASTvarDecl(int id) {
    super(id);
  }

  public ASTvarDecl(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3f1a4a92a2c420d3db78fccf6248656 (do not edit this line) */
