/* Generated By:JJTree: Do not edit this line. ASTvarDecls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvarDecls extends SimpleNode {
  public ASTvarDecls(int id) {
    super(id);
  }

  public ASTvarDecls(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=83ec47c70e71c19313a6bbbcb463bb5d (do not edit this line) */
