/* Generated By:JJTree: Do not edit this line. ASTwhen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwhen extends SimpleNode {
  public ASTwhen(int id) {
    super(id);
  }

  public ASTwhen(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=407733fff6af7f7b3aa3d5efb244fd04 (do not edit this line) */
