/* Generated By:JJTree: Do not edit this line. ASTwith.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwith extends SimpleNode {
  public ASTwith(int id) {
    super(id);
  }

  public ASTwith(pcal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=32bfd51f8ca1813bf29a1449a6ce285b (do not edit this line) */
